# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import agentos_pb2 as agentos__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agentos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KernelStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartSession = channel.unary_unary(
                '/agentos.Kernel/StartSession',
                request_serializer=agentos__pb2.StartSessionRequest.SerializeToString,
                response_deserializer=agentos__pb2.StartSessionResponse.FromString,
                _registered_method=True)
        self.CallTool = channel.unary_unary(
                '/agentos.Kernel/CallTool',
                request_serializer=agentos__pb2.CallToolRequest.SerializeToString,
                response_deserializer=agentos__pb2.CallToolResponse.FromString,
                _registered_method=True)
        self.EndSession = channel.unary_unary(
                '/agentos.Kernel/EndSession',
                request_serializer=agentos__pb2.EndSessionRequest.SerializeToString,
                response_deserializer=agentos__pb2.EndSessionResponse.FromString,
                _registered_method=True)
        self.SubscribeEvents = channel.unary_stream(
                '/agentos.Kernel/SubscribeEvents',
                request_serializer=agentos__pb2.SubscribeEventsRequest.SerializeToString,
                response_deserializer=agentos__pb2.Event.FromString,
                _registered_method=True)
        self.EmitRuntimeEvent = channel.unary_unary(
                '/agentos.Kernel/EmitRuntimeEvent',
                request_serializer=agentos__pb2.Event.SerializeToString,
                response_deserializer=agentos__pb2.EmitResponse.FromString,
                _registered_method=True)


class KernelServicer:
    """Missing associated documentation comment in .proto file."""

    def StartSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndSession(self, request, context):
        """结束会话：网关在 run 结束时调用，Kernel 据此发布 session.ended。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """订阅全量事件流（server-streaming）。网关用它收 Kernel+Runtime 事件。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmitRuntimeEvent(self, request, context):
        """Runtime 把推理事件灌进 Kernel EventBus（事件枢纽统一在 Kernel）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KernelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSession,
                    request_deserializer=agentos__pb2.StartSessionRequest.FromString,
                    response_serializer=agentos__pb2.StartSessionResponse.SerializeToString,
            ),
            'CallTool': grpc.unary_unary_rpc_method_handler(
                    servicer.CallTool,
                    request_deserializer=agentos__pb2.CallToolRequest.FromString,
                    response_serializer=agentos__pb2.CallToolResponse.SerializeToString,
            ),
            'EndSession': grpc.unary_unary_rpc_method_handler(
                    servicer.EndSession,
                    request_deserializer=agentos__pb2.EndSessionRequest.FromString,
                    response_serializer=agentos__pb2.EndSessionResponse.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=agentos__pb2.SubscribeEventsRequest.FromString,
                    response_serializer=agentos__pb2.Event.SerializeToString,
            ),
            'EmitRuntimeEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.EmitRuntimeEvent,
                    request_deserializer=agentos__pb2.Event.FromString,
                    response_serializer=agentos__pb2.EmitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentos.Kernel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentos.Kernel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Kernel:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentos.Kernel/StartSession',
            agentos__pb2.StartSessionRequest.SerializeToString,
            agentos__pb2.StartSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentos.Kernel/CallTool',
            agentos__pb2.CallToolRequest.SerializeToString,
            agentos__pb2.CallToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentos.Kernel/EndSession',
            agentos__pb2.EndSessionRequest.SerializeToString,
            agentos__pb2.EndSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agentos.Kernel/SubscribeEvents',
            agentos__pb2.SubscribeEventsRequest.SerializeToString,
            agentos__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmitRuntimeEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentos.Kernel/EmitRuntimeEvent',
            agentos__pb2.Event.SerializeToString,
            agentos__pb2.EmitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
