# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agentos.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'agentos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ragentos.proto\x12\x07\x61gentos\"E\n\x13StartSessionRequest\x12\x13\n\x0bpolicy_path\x18\x01 \x01(\t\x12\x19\n\x11sanitization_path\x18\x02 \x01(\t\"*\n\x14StartSessionResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\"H\n\x0f\x43\x61llToolRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0c\n\x04tool\x18\x02 \x01(\t\x12\x13\n\x0bparams_json\x18\x03 \x01(\t\"Z\n\x10\x43\x61llToolResponse\x12\x0f\n\x07\x61llowed\x18\x01 \x01(\x08\x12\x0f\n\x07\x65rrored\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x13\n\x0bresult_json\x18\x04 \x01(\t\"7\n\x11\x45ndSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"\x14\n\x12\x45ndSessionResponse\",\n\x16SubscribeEventsRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"\x0e\n\x0c\x45mitResponse\"\xda\x01\n\x05\x45vent\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0e\n\x06run_id\x18\x03 \x01(\t\x12\x0c\n\x04tool\x18\x04 \x01(\t\x12\x13\n\x0bparams_json\x18\x05 \x01(\t\x12\x13\n\x0bresult_json\x18\x06 \x01(\t\x12\x10\n\x08identity\x18\x07 \x01(\t\x12\x11\n\ttimestamp\x18\x08 \x01(\x03\x12,\n\x08sanitize\x18\t \x03(\x0b\x32\x1a.agentos.FieldSanitization\x12\x14\n\x0cpayload_json\x18\n \x01(\t\"4\n\x11\x46ieldSanitization\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\x10\n\x08strategy\x18\x02 \x01(\t2\xde\x02\n\x06Kernel\x12K\n\x0cStartSession\x12\x1c.agentos.StartSessionRequest\x1a\x1d.agentos.StartSessionResponse\x12?\n\x08\x43\x61llTool\x12\x18.agentos.CallToolRequest\x1a\x19.agentos.CallToolResponse\x12\x45\n\nEndSession\x12\x1a.agentos.EndSessionRequest\x1a\x1b.agentos.EndSessionResponse\x12\x44\n\x0fSubscribeEvents\x12\x1f.agentos.SubscribeEventsRequest\x1a\x0e.agentos.Event0\x01\x12\x39\n\x10\x45mitRuntimeEvent\x12\x0e.agentos.Event\x1a\x15.agentos.EmitResponseB\x1cZ\x1a\x61gentos/kernel/internal/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agentos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\032agentos/kernel/internal/pb'
  _globals['_STARTSESSIONREQUEST']._serialized_start=26
  _globals['_STARTSESSIONREQUEST']._serialized_end=95
  _globals['_STARTSESSIONRESPONSE']._serialized_start=97
  _globals['_STARTSESSIONRESPONSE']._serialized_end=139
  _globals['_CALLTOOLREQUEST']._serialized_start=141
  _globals['_CALLTOOLREQUEST']._serialized_end=213
  _globals['_CALLTOOLRESPONSE']._serialized_start=215
  _globals['_CALLTOOLRESPONSE']._serialized_end=305
  _globals['_ENDSESSIONREQUEST']._serialized_start=307
  _globals['_ENDSESSIONREQUEST']._serialized_end=362
  _globals['_ENDSESSIONRESPONSE']._serialized_start=364
  _globals['_ENDSESSIONRESPONSE']._serialized_end=384
  _globals['_SUBSCRIBEEVENTSREQUEST']._serialized_start=386
  _globals['_SUBSCRIBEEVENTSREQUEST']._serialized_end=430
  _globals['_EMITRESPONSE']._serialized_start=432
  _globals['_EMITRESPONSE']._serialized_end=446
  _globals['_EVENT']._serialized_start=449
  _globals['_EVENT']._serialized_end=667
  _globals['_FIELDSANITIZATION']._serialized_start=669
  _globals['_FIELDSANITIZATION']._serialized_end=721
  _globals['_KERNEL']._serialized_start=724
  _globals['_KERNEL']._serialized_end=1074
# @@protoc_insertion_point(module_scope)
