// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/agentos.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartSessionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PolicyPath       string                 `protobuf:"bytes,1,opt,name=policy_path,json=policyPath,proto3" json:"policy_path,omitempty"`
	SanitizationPath string                 `protobuf:"bytes,2,opt,name=sanitization_path,json=sanitizationPath,proto3" json:"sanitization_path,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StartSessionRequest) Reset() {
	*x = StartSessionRequest{}
	mi := &file_proto_agentos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionRequest) ProtoMessage() {}

func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionRequest.ProtoReflect.Descriptor instead.
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentos_proto_rawDescGZIP(), []int{0}
}

func (x *StartSessionRequest) GetPolicyPath() string {
	if x != nil {
		return x.PolicyPath
	}
	return ""
}

func (x *StartSessionRequest) GetSanitizationPath() string {
	if x != nil {
		return x.SanitizationPath
	}
	return ""
}

type StartSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionResponse) Reset() {
	*x = StartSessionResponse{}
	mi := &file_proto_agentos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionResponse) ProtoMessage() {}

func (x *StartSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionResponse.ProtoReflect.Descriptor instead.
func (*StartSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentos_proto_rawDescGZIP(), []int{1}
}

func (x *StartSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CallToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Tool          string                 `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`
	ParamsJson    string                 `protobuf:"bytes,3,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallToolRequest) Reset() {
	*x = CallToolRequest{}
	mi := &file_proto_agentos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolRequest) ProtoMessage() {}

func (x *CallToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolRequest.ProtoReflect.Descriptor instead.
func (*CallToolRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentos_proto_rawDescGZIP(), []int{2}
}

func (x *CallToolRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CallToolRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *CallToolRequest) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

type CallToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Errored       bool                   `protobuf:"varint,2,opt,name=errored,proto3" json:"errored,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ResultJson    string                 `protobuf:"bytes,4,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallToolResponse) Reset() {
	*x = CallToolResponse{}
	mi := &file_proto_agentos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolResponse) ProtoMessage() {}

func (x *CallToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolResponse.ProtoReflect.Descriptor instead.
func (*CallToolResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentos_proto_rawDescGZIP(), []int{3}
}

func (x *CallToolResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CallToolResponse) GetErrored() bool {
	if x != nil {
		return x.Errored
	}
	return false
}

func (x *CallToolResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CallToolResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

type EndSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionRequest) Reset() {
	*x = EndSessionRequest{}
	mi := &file_proto_agentos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionRequest) ProtoMessage() {}

func (x *EndSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionRequest.ProtoReflect.Descriptor instead.
func (*EndSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentos_proto_rawDescGZIP(), []int{4}
}

func (x *EndSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EndSessionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type EndSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionResponse) Reset() {
	*x = EndSessionResponse{}
	mi := &file_proto_agentos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionResponse) ProtoMessage() {}

func (x *EndSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionResponse.ProtoReflect.Descriptor instead.
func (*EndSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentos_proto_rawDescGZIP(), []int{5}
}

type SubscribeEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 预留过滤字段；MVP 网关全收后自己按 session/run 过滤。
	SessionId     string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEventsRequest) Reset() {
	*x = SubscribeEventsRequest{}
	mi := &file_proto_agentos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsRequest) ProtoMessage() {}

func (x *SubscribeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentos_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeEventsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type EmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitResponse) Reset() {
	*x = EmitResponse{}
	mi := &file_proto_agentos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitResponse) ProtoMessage() {}

func (x *EmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitResponse.ProtoReflect.Descriptor instead.
func (*EmitResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentos_proto_rawDescGZIP(), []int{7}
}

// Event 是统一事件信封。对齐 kernel/internal/eventbus.Event。
type Event struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Type       string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // tool.called | tool.denied | ... | run.started | runtime.step | run.ended
	SessionId  string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RunId      string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"` // Runtime 族事件才有
	Tool       string                 `protobuf:"bytes,4,opt,name=tool,proto3" json:"tool,omitempty"`
	ParamsJson string                 `protobuf:"bytes,5,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"` // JSON
	ResultJson string                 `protobuf:"bytes,6,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"` // JSON（已脱敏）
	Identity   string                 `protobuf:"bytes,7,opt,name=identity,proto3" json:"identity,omitempty"`
	Timestamp  int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // ns
	// 脱敏摘要：哪些字段被哪种策略处理，不含原始值。
	Sanitize []*FieldSanitization `protobuf:"bytes,9,rep,name=sanitize,proto3" json:"sanitize,omitempty"`
	// Runtime 族事件的自由负载（thought / final_answer / tool_calls / termination ...）。
	PayloadJson   string `protobuf:"bytes,10,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_agentos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_agentos_proto_rawDescGZIP(), []int{8}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Event) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Event) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *Event) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

func (x *Event) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *Event) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetSanitize() []*FieldSanitization {
	if x != nil {
		return x.Sanitize
	}
	return nil
}

func (x *Event) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type FieldSanitization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Strategy      string                 `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"` // mask | hash | redact
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldSanitization) Reset() {
	*x = FieldSanitization{}
	mi := &file_proto_agentos_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldSanitization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldSanitization) ProtoMessage() {}

func (x *FieldSanitization) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentos_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldSanitization.ProtoReflect.Descriptor instead.
func (*FieldSanitization) Descriptor() ([]byte, []int) {
	return file_proto_agentos_proto_rawDescGZIP(), []int{9}
}

func (x *FieldSanitization) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FieldSanitization) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

var File_proto_agentos_proto protoreflect.FileDescriptor

const file_proto_agentos_proto_rawDesc = "" +
	"\n" +
	"\x13proto/agentos.proto\x12\aagentos\"c\n" +
	"\x13StartSessionRequest\x12\x1f\n" +
	"\vpolicy_path\x18\x01 \x01(\tR\n" +
	"policyPath\x12+\n" +
	"\x11sanitization_path\x18\x02 \x01(\tR\x10sanitizationPath\"5\n" +
	"\x14StartSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"e\n" +
	"\x0fCallToolRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04tool\x18\x02 \x01(\tR\x04tool\x12\x1f\n" +
	"\vparams_json\x18\x03 \x01(\tR\n" +
	"paramsJson\"\x81\x01\n" +
	"\x10CallToolResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x18\n" +
	"\aerrored\x18\x02 \x01(\bR\aerrored\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1f\n" +
	"\vresult_json\x18\x04 \x01(\tR\n" +
	"resultJson\"J\n" +
	"\x11EndSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x14\n" +
	"\x12EndSessionResponse\"7\n" +
	"\x16SubscribeEventsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x0e\n" +
	"\fEmitResponse\"\xbc\x02\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12\x12\n" +
	"\x04tool\x18\x04 \x01(\tR\x04tool\x12\x1f\n" +
	"\vparams_json\x18\x05 \x01(\tR\n" +
	"paramsJson\x12\x1f\n" +
	"\vresult_json\x18\x06 \x01(\tR\n" +
	"resultJson\x12\x1a\n" +
	"\bidentity\x18\a \x01(\tR\bidentity\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x126\n" +
	"\bsanitize\x18\t \x03(\v2\x1a.agentos.FieldSanitizationR\bsanitize\x12!\n" +
	"\fpayload_json\x18\n" +
	" \x01(\tR\vpayloadJson\"E\n" +
	"\x11FieldSanitization\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1a\n" +
	"\bstrategy\x18\x02 \x01(\tR\bstrategy2\xde\x02\n" +
	"\x06Kernel\x12K\n" +
	"\fStartSession\x12\x1c.agentos.StartSessionRequest\x1a\x1d.agentos.StartSessionResponse\x12?\n" +
	"\bCallTool\x12\x18.agentos.CallToolRequest\x1a\x19.agentos.CallToolResponse\x12E\n" +
	"\n" +
	"EndSession\x12\x1a.agentos.EndSessionRequest\x1a\x1b.agentos.EndSessionResponse\x12D\n" +
	"\x0fSubscribeEvents\x12\x1f.agentos.SubscribeEventsRequest\x1a\x0e.agentos.Event0\x01\x129\n" +
	"\x10EmitRuntimeEvent\x12\x0e.agentos.Event\x1a\x15.agentos.EmitResponseB\x1cZ\x1aagentos/kernel/internal/pbb\x06proto3"

var (
	file_proto_agentos_proto_rawDescOnce sync.Once
	file_proto_agentos_proto_rawDescData []byte
)

func file_proto_agentos_proto_rawDescGZIP() []byte {
	file_proto_agentos_proto_rawDescOnce.Do(func() {
		file_proto_agentos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agentos_proto_rawDesc), len(file_proto_agentos_proto_rawDesc)))
	})
	return file_proto_agentos_proto_rawDescData
}

var file_proto_agentos_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_agentos_proto_goTypes = []any{
	(*StartSessionRequest)(nil),    // 0: agentos.StartSessionRequest
	(*StartSessionResponse)(nil),   // 1: agentos.StartSessionResponse
	(*CallToolRequest)(nil),        // 2: agentos.CallToolRequest
	(*CallToolResponse)(nil),       // 3: agentos.CallToolResponse
	(*EndSessionRequest)(nil),      // 4: agentos.EndSessionRequest
	(*EndSessionResponse)(nil),     // 5: agentos.EndSessionResponse
	(*SubscribeEventsRequest)(nil), // 6: agentos.SubscribeEventsRequest
	(*EmitResponse)(nil),           // 7: agentos.EmitResponse
	(*Event)(nil),                  // 8: agentos.Event
	(*FieldSanitization)(nil),      // 9: agentos.FieldSanitization
}
var file_proto_agentos_proto_depIdxs = []int32{
	9, // 0: agentos.Event.sanitize:type_name -> agentos.FieldSanitization
	0, // 1: agentos.Kernel.StartSession:input_type -> agentos.StartSessionRequest
	2, // 2: agentos.Kernel.CallTool:input_type -> agentos.CallToolRequest
	4, // 3: agentos.Kernel.EndSession:input_type -> agentos.EndSessionRequest
	6, // 4: agentos.Kernel.SubscribeEvents:input_type -> agentos.SubscribeEventsRequest
	8, // 5: agentos.Kernel.EmitRuntimeEvent:input_type -> agentos.Event
	1, // 6: agentos.Kernel.StartSession:output_type -> agentos.StartSessionResponse
	3, // 7: agentos.Kernel.CallTool:output_type -> agentos.CallToolResponse
	5, // 8: agentos.Kernel.EndSession:output_type -> agentos.EndSessionResponse
	8, // 9: agentos.Kernel.SubscribeEvents:output_type -> agentos.Event
	7, // 10: agentos.Kernel.EmitRuntimeEvent:output_type -> agentos.EmitResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_agentos_proto_init() }
func file_proto_agentos_proto_init() {
	if File_proto_agentos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agentos_proto_rawDesc), len(file_proto_agentos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agentos_proto_goTypes,
		DependencyIndexes: file_proto_agentos_proto_depIdxs,
		MessageInfos:      file_proto_agentos_proto_msgTypes,
	}.Build()
	File_proto_agentos_proto = out.File
	file_proto_agentos_proto_goTypes = nil
	file_proto_agentos_proto_depIdxs = nil
}
